### ISSUE TITLE
Request: Markdown version of whitepaper

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Whitepaper#7]
PDF is great, but a markdown version would be even better - any chance you could upload a version which was converted to markdown? Thanks

**Comment by wisecracka** [comment]
I can look into it but I have no real experience working with markdown. Might take some time. If anyone else can help, please do :D

**Comment by jring-o** [comment]
As discussed and agreed upon by majority on slack, a .pdf attached to the https://gridcoin.us site would be ideal.

something like https://gridcoin.us/whitepaper.pdf or https://gridcoin.us/gridcoin.pdf

in the future, if someone wants they can make a markdown version. for marketing reasons, the above route is the clear path to take at this time.

blue papers/technical white papers are more likely to be markdown for github as they are directed more towards developers while white papers are more marketing and PR tools and should maintain the simple access, printability, and design offered by .pdf.

**Comment by barton2526** [comment]
Markdown version of whitepaper is now in the repo.  Thanks @wisecracka!
